#!/bin/bash
#
# QUEKO Benchmark Aggregation Script (Phase 3 of 3)
#
# Collects results from array job outputs and generates a summary CSV.
# This script runs after all array tasks complete (or timeout).
#
# The aggregator checks for QPY output files to determine task status:
# - If QPY file exists: task completed successfully
# - If QPY file missing: task failed or timed out
#
# Usage:
#   sbatch --dependency=afterany:<array_job_id> slurm_aggregate.sh
#
# The 'afterany' dependency ensures this runs even if some array tasks fail,
# allowing us to collect partial results.
#
# References:
#   - Google Shell Style Guide: https://google.github.io/styleguide/shellguide.html

#SBATCH --job-name=quariadne-aggregate
#SBATCH --partition=normal
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --output=aggregate_%j.out
#SBATCH --error=aggregate_%j.err
#SBATCH --uenv=prgenv-gnu/25.11:v1

set -euo pipefail

# ============================================================================
# Configuration
# ============================================================================

# Work directory follows the same convention as setup and array scripts:
# - On cluster: $SCRATCH/quariadne-benchmark
# - Locally: ./quariadne-benchmark
if [[ -n "${SCRATCH:-}" ]]; then
  WORK_DIR="${SCRATCH}/quariadne-benchmark"
else
  WORK_DIR="$(pwd)/quariadne-benchmark"
fi

readonly WORK_DIR

# Task list generated by setup script contains all (circuit, backend, method) combinations
readonly TASK_LIST="${WORK_DIR}/task_list.txt"

# Results directory where array jobs write QPY output files
readonly RESULTS_DIR="${WORK_DIR}/results"

# Summary CSV will contain one row per task with completion status
readonly SUMMARY_FILE="${RESULTS_DIR}/summary.csv"

# ============================================================================
# Header
# ============================================================================

echo "=========================================="
echo "QUEKO Benchmark Aggregation (Phase 3)"
echo "=========================================="
echo "Work directory: ${WORK_DIR}"
echo "Results directory: ${RESULTS_DIR}"
echo ""

# ============================================================================
# Count Results
# ============================================================================

# Count total tasks from task list (one line per task)
total_tasks=$(wc -l < "${TASK_LIST}")

# Count completed tasks by counting QPY output files
# Each successful transpilation produces one QPY file
completed_qpy=$(find "${RESULTS_DIR}" -name "*.qpy" -type f | wc -l)

echo "Total tasks: ${total_tasks}"
echo "Completed (QPY files): ${completed_qpy}"
echo ""

# ============================================================================
# Generate Summary CSV
# ============================================================================

echo "Generating summary CSV..."

# Write CSV header
echo "circuit,backend,method,status" > "${SUMMARY_FILE}"

# Process each task from the task list
# Task format: circuit_path|backend|method (pipe-delimited)
while IFS='|' read -r circuit_path backend method; do
  # Extract circuit name from path (e.g., "16QBT_05CYC_TFL_0" from "QUEKO-benchmark/.../16QBT_05CYC_TFL_0.qasm")
  circuit_name=$(basename "${circuit_path}" .qasm)

  # QPY files are named: {method}_{circuit_name}.qpy
  qpy_file="${RESULTS_DIR}/${method}_${circuit_name}.qpy"

  # Check if output file exists to determine completion status
  if [[ -f "${qpy_file}" ]]; then
    status="completed"
  else
    status="missing"
  fi

  # Append row to summary CSV
  echo "${circuit_name},${backend},${method},${status}" >> "${SUMMARY_FILE}"
done < "${TASK_LIST}"

echo "Summary written to: ${SUMMARY_FILE}"

# ============================================================================
# Statistics
# ============================================================================

echo ""
echo "=========================================="
echo "Aggregation Complete"
echo "=========================================="

# Count completed and missing from summary CSV
# Use '|| true' to prevent grep from failing if no matches (exit code 1)
completed=$(grep -c ",completed$" "${SUMMARY_FILE}" || true)
missing=$(grep -c ",missing$" "${SUMMARY_FILE}" || true)

echo "Completed: ${completed}"
echo "Missing: ${missing}"
echo "Total: ${total_tasks}"
